# Site settings
title:          잼킷 개발 레시피 모음
description:    잼킷으로 미니앱을 개발할 때 바로 활용 가능한 레시피 모음
url:            https://jamkit-recipes-ko.github.io

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Hanyeol Cho
  url:          https://github.com/hanyeol
  email:        hanyeol.cho@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
